[project]
name = "eadi-openenv"
version = "0.1.0"
description = "Emotion-Aware Decision Intelligence OpenEnv"
authors = [{ name = "Sakshi Selmokar" }]

dependencies = [
  "fastapi",
  "uvicorn",
  "openenv-core>=0.2.0"
]

[project.scripts]
server = "server.app:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"